#!/bin/sh

#Licensed under the BSD 3-clause license
#Copyright (c) 2021, Privacy_Dragon
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without
#modification, are permitted provided that the following conditions are met:
#
#1. Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#2. Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#3. Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
#FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
#SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if echo "$1" | grep -q "\-\-version"; then
  echo "Current version: 0.1.2 -- Beta"
  exit 0
fi

if echo "$1" | grep -q "\-\-help"; then
  echo "Usage: local_installer <FILE>"; echo "This program installs a .rmp or .deb package locally and the script is usable for any user.\nBugs can be reported via Github or by sending an e-mail to <privacy_dragon@tutanota.com>."
  exit 0
fi

if echo "$1" | grep -q "/"; then
  path=$1
  file=${path##*/}
else
  file=$1
fi

if echo "$1" | grep -q ".deb"; then
  echo "Application to install: " $1
  echo "Detected .deb structure."
  #Here installing of .deb files is handled.
  tmpdir=$HOME/.cache/$file
  mkdir $tmpdir
  cp $1 $tmpdir
  cd $tmpdir
  ar -x $file
  if ! ls | grep -q "data.tar"; then cd */.; fi
  if ls | grep -q ".tar.xz"; then tar -xJf data.tar.xz; #If the data file is a .xz file, it should be handled as .xz
  elif ls | grep -q ".tar.gz"; then tar -xzf data.tar.gz; #Though if the data file is a .gz file, it should be handled as .gz
  else echo "ERROR: file type of data archive was not understood"; fi #If the file is not a .gz file and not a .xz file, give an error.
  cd usr
  cp -r * $HOME/.local/ #Copy the files to the .local folder, where all local programs and stuff is standard stored.
  if ! echo $PATH | grep /\.local/bin; then export PATH=$PATH:~/.local/bin; fi #Add .local/bin to the PATH if it isn't yet.
  if ! cat $HOME/.bashrc | grep /\.local/bin; then echo "export PATH=$PATH:~/.local/bin"; fi #Make sure that .local/bin is added to the Path every time.
  cd ../../../
  rm -rf $tmpdir #Clean up the temporary dir.
  echo "Installation was successful!"
  exit 0
fi
if echo "$1" | grep -q ".rpm"; then
  echo "Application to install: " $1 
  echo "Detected .rpm structure."
  #here installing of .rpm files is handled.
  tmpdir=$HOME/.cache/$file
  mkdir $tmpdir
  rpm2cpio $1 | cpio -id -D $tmpdir #Extract the rpm file.
  cd $tmpdir/usr
  cp -r * $HOME/.local/ #Copy the files to the .local folder, where all local programs and stuff is standard stored.
  if ! echo $PATH | grep /\.local/bin; then export PATH=$PATH:~/.local/bin; fi #Add .local/bin to the path if it isn't yet.
  if ! cat $HOME/.bashrc | grep /\.local/bin; then echo "export PATH=$PATH:~/.local/bin"; fi #Make sure that .local/bin is added to the Path every time.
  cd ../../../
  rm -rf $tmpdir #Clean up the temporary dir.
  echo "Installation was successful!"
  exit 0
fi
#If the script comes here, the input was not 'valid'
echo "FATAL ERROR: not a valid input.\nUsage: local_installer [--help] | [--version] | <FILE>"
exit 1
